const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../site/assets/analytics.js'),'utf8');
function boot(url,disabled=false){const events=[],handlers={},scripts=[],storage=new Map(disabled?[['umami.disabled','1']]:[]);const u=new URL(url);const window={umami:{track:(...args)=>events.push(args)}};const document={currentScript:{getAttribute:()=> 'test'},createElement:()=>({setAttribute(){}}),head:{appendChild:s=>scripts.push(s)},addEventListener:(n,f)=>handlers[n]=f};const c={window,document,location:u,navigator:{},URL,URLSearchParams,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};vm.runInNewContext(source,c);return{...c,events,handlers,scripts,storage};}
for(const url of ['http://localhost:8767/','http://127.0.0.1:8767/','https://yoramfriedman.com/yossibenabu-site/'])assert.equal(boot(url).scripts.length,0);
assert.equal(boot('https://yossibenabu.com/?analytics=off').scripts.length,0);assert.equal(boot('https://yossibenabu.com/',true).scripts.length,0);assert.equal(boot('https://yossibenabu.com/?analytics=on',true).scripts.length,1);
const b=boot('https://yossibenabu.com/index.html');let p=b.window.websiteAnalyticsBeforeSend('event',{url:'/index.html?artwork=private&email=a@example.com&utm_source=gallery#about',referrer:'https://example.com/?email=private'});assert.equal(p.url,'/?utm_source=gallery');assert.equal(p.referrer,'https://example.com/');assert.equal(b.window.websiteAnalyticsBeforeSend('event',{url:'/yossibenabu-site/work/test/index.html'}).url,'/work/test/');
function click(href,attrs={},title){const a={getAttribute:k=>k==='href'?href:attrs[k],hasAttribute:k=>k in attrs,closest:s=>s==='a[href]'?a:s==='[data-viewer]'&&title?{getAttribute:()=>title}:null};b.handlers.click({target:a});}
click('/work/test/');click('/assets/a.webp',{'data-view':'Side'},'Example');click('mailto:info@yossibenabu.com?body=secret');click('https://sbfinearts.com/artist/yossi-ben-abu');click('/index.html#inquire');b.handlers.submit({target:{matches:()=>true,value:'secret inquiry'}});
assert.deepEqual(b.events.map(e=>e[0]),['artwork-explore','artwork-view-change','email-click','gallery-click','inquiry-click','inquiry-submit-attempt']);assert(!JSON.stringify(b.events).includes('secret'));assert.equal(b.events.length,6);console.log('Passed: domain exclusions, browser opt-out/re-enable, URL normalization, query privacy, six action routes, no form content collection.');
